- name: Running Ansible Deployment
  hosts: nodes

  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world 123 from thisiscpta'.
      copy:
        content: hello-world-123 thisisicpta
        dest: /tmp/testfile.txt
        mode: 0644
    - name: echo asset
      debug:
        msg: "{{ whichasset }}"
    - name: echo environment
      debug:
        msg: "{{ whichenv }}"
    - name: transfer package
      copy:
        src: "{{ whichasset }}"
        dest: /home/ansibleuser/"{{ whichasset }}"
        owner: ansibleuser
        group: ansibleuser
        mode: 0644
 
#  dest: /home/ansibleuser/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar
