# This is a basic workflow to help you get started with Actions

name: Deploy via Ansible

  # Allows you to run this workflow manually from the Actions tab
on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
      which-asset:
        required: true
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
         echo Hello, world!
         ansible-playbook -u ansibleuser --extra-vars "which-asset=whatever" -i ansible/inventory ansible/hello-world.yaml 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build, ${{ inputs.which-env }}, ${{ inputs.which-asset }}
          echo test, and deploy your project.
