on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
        
jobs:
 sona_scan:
    runs-on: ubuntu-latest
    name: SonarQube scan
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday. ${{ inputs.config-path }}"
      - name: Every time
        run: echo "This step will always run => ${{ secrets.URL }}"
      - name: Execute Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: "./"
          args: >
            -Dsonar.verbose=true
            -Dsonar.organization=thisiscpta
            -Dsonar.projectKey=thisiscpta_github-action-maven-example-start

        env:
            SONAR_TOKEN: "ac6f80950a393d4b6ba0c524b13125a773b738cd"
            SONAR_HOST_URL: "https://sonarcloud.io"

              
