on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
        
jobs:
 sona_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday. ${{ inputs.config-path }}"
      - name: Every time
        run: echo "This step will always run. ${{ secrets.envPAT }}"
              
