on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
       
jobs:
 deploy_sit:
    runs-on: ubuntu-latest
    environment: 
      name: SIT
      url: https://github.com
    name: Deplyo to SIT
    steps:
      - name: Get environment
        run: |
             echo "projectKey=${{ github.repository_owner }}_$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Print input variables
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "inputs.which-env = ${{ inputs.which-env }}, secrects=${{ secrets.SIT_USERNAME}}, owner=${{ github.repository_owner }}, projectKey= ${{ env.projectKey }}, truncate repo=${GITHUB_REPOSITORY#*/}"


