on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
      which-asset:
        required: true
        type: string
      which-issue:
        required: true
        type: string
        
jobs:
 prepare_workspace:
    runs-on: self-hosted
    name: Prepare workspace
    steps:
       - name: get repo
         uses: actions/checkout@v3
      
 get_release_asset:
    runs-on: self-hosted
    needs: [prepare_workspace]
    environment: 
      name: SIT
      url:  ${{ vars.URL }}
    name: Download release asset
    steps:
      - name: Get environment
        run: |
             echo "projectKey=${{ github.repository_owner }}_$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Print XXXX
        run: |
             echo "XXXX which-asset=${{ inputs.which-asset }}" 
             echo "${{ inputs.which-env }} variable URL : ${{ vars.URL }}"
             echo "${{ inputs.which-env }} password secrets : ${{ secrets.SIT_PASSWORD }}"
             echo "${{ inputs.which-env }} username secrets : ${{ secrets.SIT_USERNAME }}"
      - name: Get release assest
        id: download
        uses: actions/download-artifact@v3
        with:
            name: ${{ inputs.which-asset }}
            path: ansible/files
      - name: 'Echo download path'
        run: |
           echo ${{steps.download.outputs.download-path}}
           echo ${{ github.repository }}
       
 deploy_using_ansible:
       runs-on: self-hosted
       needs: [get_release_asset]
       name: Deploying to ${{ inputs.which-env }} using Ansible
       steps:
       - name: Run a one-line script
         run: |
             echo Hello, world ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
             echo ${{ inputs.which-issue}}
             ansible-playbook -u ansibleuser --extra-vars "whichenv=${{ inputs.which-env }} whichasset=${{ inputs.which-asset }} whichissue=${{ inputs.which-issue }} " -i ansible/inventory ansible/hello-world.yaml 
