on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
      which-asset:
        required: true
        type: string
jobs:
 get_release_asset:
    runs-on: self-hosted
    environment: 
      name: SIT
      url:  ${{ vars.URL }}
    name: Download release asset
    steps:
      - name: Get environment
        run: |
             echo "projectKey=${{ github.repository_owner }}_$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Print
        run: |
             echo "which-env=${{ inputs.which-env }}" 
             echo "${{ inputs.which-env }} variable URL : ${{ vars.URL }}"
             echo "${{ inputs.which-env }} password secrets : ${{ secrets.SIT_PASSWORD }}"
             echo "${{ inputs.which-env }} username secrets : ${{ secrets.SIT_USERNAME }}"
      - name: Get release assest
        id: download
        uses: actions/download-artifact@v3
        with:
            name: ${{ inputs.which-asset }}
            path: /tmp
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

 deploy_using_ansible:
       runs-on: self-hosted
       needs: [get_release_asset]
       name: Deploying to ${{ inputs.which-env }} using Ansible
       steps:
       - uses: actions/checkout@v3
       - name: Move file
         run: |
           mv /tmp/${{ inputs.which-asset }} ansible/files
       - name: Run a one-line script
         run: |
             echo Hello, world!
             ansible-playbook -u ansibleuser --extra-vars "whichenv=${{ inputs.which-env }} whichasset=${{ inputs.which-asset }}" -i ansible/inventory ansible/hello-world.yaml 

