on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
      which-asset:
        required: true
        type: string
jobs:
 deploy_sit:
    runs-on: self-hosted
    environment: 
      name: SIT
      url:  ${{ vars.URL }}
    name: Deploy to ${{ inputs.which-env }}
    steps:
      - name: Get environment
        run: |
             echo "projectKey=${{ github.repository_owner }}_$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Print
        run: |
             echo "which-env=${{ inputs.which-env }}" 
             echo "${{ inputs.which-env }} variable URL : ${{ vars.URL }}"
             echo "${{ inputs.which-env }} password secrets : ${{ secrets.SIT_PASSWORD }}"
             echo "${{ inputs.which-env }} username secrets : ${{ secrets.SIT_USERNAME }}"
      - name: Get release assest
        id: download
        uses: actions/download-artifact@v3
        with:
            name: ${{ inputs.which-asset }}
            path: ansible/file
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
  
 deploy_to_env:
      name: Deploy to Ansible nodes
      uses: ./.github/workflows/ansiblecall.yml
      with:
         which-env: ${{ inputs.which-env }}
         which-asset: ${{ inputs.which-asset }}   
      secrets:
            inherit

            
