on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
       
jobs:
 deploy_sit:
    runs-on: ubuntu-latest
    environment: 
      name: SIT
      url:  ${{ vars.URL }}
    name: Deplyo to SIT
    steps:
      - name: Get environment
        run: |
             echo "projectKey=${{ github.repository_owner }}_$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Print
        run: |
             echo "which-env=${{ inputs.which-env }} OK" 
             echo "repository variable URL : ${{ vars.URL }}"
             echo "password secrets : ${{ secrets.SIT_PASSWORD }}"
             echo "username secrets : ${{ secrets.SIT_USERNAME }}"
