on:
  workflow_call:
    inputs:
      which-env:
        required: true
        type: string
       
jobs:
 deploy_sit:
    runs-on: ubuntu-latest
    environment: 
      name: SIT
      url:  ${{ vars.URL }}
    name: Deploy to ${{ inputs.which-env }}
    steps:
      - name: Get environment
        run: |
             echo "projectKey=${{ github.repository_owner }}_$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Print
        run: |
             echo "which-env=${{ inputs.which-env }}" 
             echo "${{ inputs.which-env }} variable URL : ${{ vars.URL }}"
             echo "${{ inputs.which-env }} password secrets : ${{ secrets.SIT_PASSWORD }}"
             echo "${{ inputs.which-env }} username secrets : ${{ secrets.SIT_USERNAME }}"
             
